language: java

jdk:
  - openjdk8

notifications:
  email: false

cache:
  directories:
    - '$HOME/.m2'

script:
  - export TZ=Asia/Shanghai
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V